// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package categorymodule

import (
	controller "github.com/katatrina/go12-service/modules/category/infras/controller/http"
	repository "github.com/katatrina/go12-service/modules/category/infras/repository/mysql"
	"github.com/katatrina/go12-service/modules/category/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeCategoryController(db *gorm.DB) *controller.CategoryController {
	categoryRepository := repository.NewCategoryRepository(db)
	createCommandHandler := service.NewCreateCommandHandler(categoryRepository)
	getByIDQueryHandler := service.NewGetDetailQueryHandler(categoryRepository)
	listCategoriesQueryHandler := service.NewListCategoriesQueryHandler(categoryRepository)
	updateByIDCommandHandler := service.NewUpdateByIDCommandHandler(categoryRepository)
	deleteByIDCommandHandler := service.NewDeleteByIDCommandHandler(categoryRepository)
	categoryHTTPController := controller.NewCategoryController(createCommandHandler, getByIDQueryHandler, listCategoriesQueryHandler, updateByIDCommandHandler, deleteByIDCommandHandler)
	return categoryHTTPController
}
