// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package categorymodule

import (
	"github.com/katatrina/go12-service/modules/category/infras/controller/http-gin"
	"github.com/katatrina/go12-service/modules/category/infras/repository/gorm-mysql"
	"github.com/katatrina/go12-service/modules/category/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeCategoryController(db *gorm.DB) *categoryhttpgin.CategoryHTTPController {
	categoryRepository := categorygormmysql.NewCategoryRepository(db)
	createCommandHandler := categoryservice.NewCreateCommandHandler(categoryRepository)
	getDetailQueryHandler := categoryservice.NewGetDetailQueryHandler(categoryRepository)
	listCategoriesQueryHandler := categoryservice.NewListCategoriesQueryHandler(categoryRepository)
	updateByIDCommandHandler := categoryservice.NewUpdateByIDCommandHandler(categoryRepository)
	deleteByIDCommandHandler := categoryservice.NewDeleteByIDCommandHandler(categoryRepository)
	categoryHTTPController := categoryhttpgin.NewCategoryHTTPController(createCommandHandler, getDetailQueryHandler, listCategoriesQueryHandler, updateByIDCommandHandler, deleteByIDCommandHandler)
	return categoryHTTPController
}
