// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restaurantmodule

import (
	"github.com/katatrina/go12-service/modules/restaurant/infras/controller/http"
	"github.com/katatrina/go12-service/modules/restaurant/infras/repository/mysql"
	"github.com/katatrina/go12-service/modules/restaurant/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRestaurantController(db *gorm.DB) *controller.RestaurantController {
	restaurantRepository := repository.NewRestaurantRepository(db)
	createCommandHandler := service.NewCreateCommandHandler(restaurantRepository)
	getByIDQueryHandler := service.NewGetDetailQueryHandler(restaurantRepository)
	listRestaurantsQueryHandler := service.NewListRestaurantsQueryHandler(restaurantRepository)
	updateByIDCommandHandler := service.NewUpdateByIDCommandHandler(restaurantRepository)
	deleteByIDCommandHandler := service.NewDeleteByIDCommandHandler(restaurantRepository)
	restaurantController := controller.NewRestaurantController(createCommandHandler, getByIDQueryHandler, listRestaurantsQueryHandler, updateByIDCommandHandler, deleteByIDCommandHandler)
	return restaurantController
}
