// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restaurantmodule

import (
	"github.com/katatrina/go12-service/modules/restaurant/infras/controller/http"
	"github.com/katatrina/go12-service/modules/restaurant/infras/repository/mysql"
	"github.com/katatrina/go12-service/modules/restaurant/infras/repository/rpc"
	"github.com/katatrina/go12-service/modules/restaurant/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeRestaurantController(db *gorm.DB) *httpcontroller.RestaurantController {
	restaurantRepository := mysqlrepository.NewRestaurantRepository(db)
	createCommandHandler := restaurantservice.NewCreateCommandHandler(restaurantRepository)
	getByIDQueryHandler := restaurantservice.NewGetDetailQueryHandler(restaurantRepository)
	categoryRPCClient := rpcclient.NewCategoryRPCClient(db)
	listRestaurantsQueryHandler := restaurantservice.NewListRestaurantsQueryHandler(restaurantRepository, categoryRPCClient)
	updateByIDCommandHandler := restaurantservice.NewUpdateByIDCommandHandler(restaurantRepository)
	deleteByIDCommandHandler := restaurantservice.NewDeleteByIDCommandHandler(restaurantRepository)
	restaurantController := httpcontroller.NewRestaurantController(createCommandHandler, getByIDQueryHandler, listRestaurantsQueryHandler, updateByIDCommandHandler, deleteByIDCommandHandler)
	return restaurantController
}
