// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package categorymodule

import (
	"github.com/katatrina/go12-service/modules/categorymodule/infras/controller/http-gin"
	"github.com/katatrina/go12-service/modules/categorymodule/infras/repository/gorm-mysql"
	"github.com/katatrina/go12-service/modules/categorymodule/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeCategoryController(db *gorm.DB) *categoryhttpgin.CategoryHTTPController {
	categoryRepository := categorygormmysql.NewCategoryRepository(db)
	categoryService := categoryservice.NewCategoryService(categoryRepository)
	getDetailQueryHandler := categoryservice.NewGetDetailQueryHandler(categoryRepository)
	categoryHTTPController := categoryhttpgin.NewCategoryHTTPController(categoryService, getDetailQueryHandler)
	return categoryHTTPController
}
